# Generated by Django 5.2.16 on 2026-09-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, default='', help_text="Snapshot of the actor's role (tenant/owner/admin/system) at event time.", max_length=20)),
                ('actor_email', models.EmailField(blank=True, default='', help_text="Snapshot of the actor's email (safe for display). Redacted when not appropriate.", max_length=254)),
                ('actor_display', models.CharField(blank=True, default='', help_text="Human-readable display name for the actor (e.g. 'John Doe', 'System').", max_length=255)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('user', 'User'), ('booking', 'Booking'), ('payment', 'Payment'), ('property', 'Property'), ('vehicle', 'Vehicle'), ('admin', 'Admin'), ('security', 'Security'), ('system', 'System'), ('notification', 'Notification'), ('other', 'Other')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=20)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('target_display', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. NULL indicates a SYSTEM event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='audit_audit_categor_d6483d_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx'), models.Index(fields=['result', 'created_at'], name='audit_audit_result_d401d9_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['target_type', 'target_id', 'created_at'], name='audit_audit_target__a22730_idx')],
            },
        ),
    ]
