"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["cellulolytic-nonshredding-kena.ngrok-free.dev", "localhost", "127.0.0.1"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "accounts",
    "properties",
    "interactions",
    "bookings",
    "payments",
    "site_settings",
    "audit",

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}
AUTH_USER_MODEL = "accounts.User"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.permissions.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")

# ── Transactional email ──────────────────────────────────────────────────
# DEVELOPMENT default uses Gmail SMTP so emails reach a real inbox while the
# app is running locally. Every value can be overridden via environment
# variables, so production is NOT permanently coupled to Gmail -- swapping
# providers later only requires changing EMAIL_* in the environment.
#
# Credentials are NEVER hard-coded here. Provide them through the .env file
# (see "Gmail App Password" step); .env is gitignored.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
# Default to 465 + SSL (SMTPS). Some networks block STARTTLS on port 587, so
# port 465 is the resilient default for Gmail. Override via env as needed.
EMAIL_PORT = config("EMAIL_PORT", default=465, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=False, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=True, cast=bool)
# Timeout (seconds) for each SMTP operation to avoid hanging the request.
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=30, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
# DEFAULT_FROM_EMAIL falls back to the configured SMTP sender.
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default=config("EMAIL_HOST_USER", default="no-reply@example.com"),
)
DEFAULT_FROM_NAME = config("DEFAULT_FROM_NAME", default="Property Rental System")

# Base URL of the React frontend used to build email call-to-action links.
FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="http://localhost:3000")

# ── Chapa payment gateway ────────────────────────────────────────────────
# The secret key is server-side ONLY and must never reach the browser. In
# development use Chapa TEST/SANDBOX keys. All values come from the .env file
# (gitignored) -- never hard-code credentials in source.
CHAPA_SECRET_KEY = config("CHAPA_SECRET_KEY", default="")
CHAPA_PUBLIC_KEY = config("CHAPA_PUBLIC_KEY", default="")
CHAPA_WEBHOOK_SECRET = config("CHAPA_WEBHOOK_SECRET", default="")
CHAPA_CURRENCY = config("CHAPA_CURRENCY", default="ETB")
# Base API endpoints. Override in local dev to point at a tunneled URL.
CHAPA_API_BASE = config("CHAPA_API_BASE", default="https://api.chapa.co/v1")
# Callback/return/webhook URLs must be publicly reachable by Chapa. In local
# dev point these at a temporary HTTPS tunnel (never localhost). Configured via
# environment, never hard-coded.
CHAPA_CALLBACK_URL = config("CHAPA_CALLBACK_URL", default="")
CHAPA_RETURN_URL = config("CHAPA_RETURN_URL", default="")
CHAPA_WEBHOOK_URL = config("CHAPA_WEBHOOK_URL", default="")

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"