# Generated by Django 5.2.16 on 2026-08-18 06:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0004_property_currency_subscriptionplan_featuredlisting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(editable=False, help_text='Unique transaction identifier.', max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('telebirr', 'Telebirr'), ('chapa', 'Chapa'), ('cbe_birr', 'CBE Birr'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('other', 'Other')], help_text='Payment method used.', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='Reference from the external payment provider (e.g., transaction ID from Chapa).', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(help_text='Currency for this transaction.', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='initiated', help_text='Current payment status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='The booking this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='bookings.booking')),
                ('payer', models.ForeignKey(help_text='The user making the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_as_payer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_reference', models.CharField(editable=False, help_text='Unique refund identifier.', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(help_text='Currency for this refund.', max_length=3)),
                ('reason', models.TextField(blank=True, help_text='Reason for the refund.', null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', help_text='Current refund status.', max_length=20)),
                ('provider_refund_reference', models.CharField(blank=True, help_text='Reference from the external payment provider for the refund.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed.', null=True)),
                ('payment', models.ForeignKey(help_text='The payment transaction being refunded.', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_reference', models.CharField(editable=False, help_text='Unique payout identifier.', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to the owner/company.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(help_text='Currency for the payout.', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payout status.', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payout was processed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='The booking this payout is for.', on_delete=django.db.models.deletion.CASCADE, related_name='owner_payouts', to='bookings.booking')),
                ('company', models.ForeignKey(blank=True, help_text='Company receiving the payout. NULL if individual owner receives it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_payouts_as_company', to='properties.company')),
                ('owner', models.ForeignKey(blank=True, help_text='Individual owner receiving the payout. NULL if company receives it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_payouts_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Payout',
                'verbose_name_plural': 'Owner Payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='payments_ow_booking_5b4a84_idx'), models.Index(fields=['owner', 'status'], name='payments_ow_owner_i_3d644e_idx'), models.Index(fields=['company', 'status'], name='payments_ow_company_5cb557_idx'), models.Index(fields=['status'], name='payments_ow_status_9fdf0e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('owner__isnull', False)), models.Q(('company__isnull', False), ('owner__isnull', True)), _connector='OR'), name='payout_belongs_to_exactly_one_recipient')],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_bec69e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer', 'status'], name='payments_pa_payer_i_2437ab_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='payments_re_payment_4444a0_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='payments_re_status_715c3a_idx'),
        ),
    ]
