# Generated by Django 5.2.16 on 2026-08-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'Telebirr'), ('chapa', 'Chapa'), ('cbe_birr', 'CBE Birr'), ('cash', 'Cash'), ('other', 'Other')], help_text='Payment method used.', max_length=20),
        ),
    ]
