# Generated by Django 5.2.16 on 2026-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Provider transaction reference (e.g., Chapa tx_ref) used for the callback/webhook round-trip.', max_length=50, null=True, unique=True),
        ),
    ]
