# Generated by Django 5.2.16 on 2026-09-10 17:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenttransaction_tx_ref'),
        ('properties', '0011_subscription_purchased_billing_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(editable=False, help_text='Unique transaction identifier.', max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('telebirr', 'Telebirr'), ('chapa', 'Chapa'), ('cbe_birr', 'CBE Birr'), ('cash', 'Cash'), ('other', 'Other')], help_text='Payment method used.', max_length=20)),
                ('tx_ref', models.CharField(blank=True, help_text='Provider transaction reference (e.g., Chapa tx_ref).', max_length=50, null=True, unique=True)),
                ('provider_reference', models.CharField(blank=True, help_text='Reference from the external payment provider.', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(help_text='Currency for this transaction.', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='initiated', help_text='Current payment status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(help_text='The user making the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(help_text='The subscription this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='payments_su_subscri_c084b1_idx'), models.Index(fields=['payer', 'status'], name='payments_su_payer_i_ede64a_idx'), models.Index(fields=['status'], name='payments_su_status_ed850e_idx')],
            },
        ),
    ]
