# Generated by hands: transforms the legacy manual Testimonial table into a
# review-backed moderation entity.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_legacy_manual_testimonials(apps, schema_editor):
    """Remove manual/static testimonial rows.

    The old 'Testimonial' model stored hand-curated name/role/text/image data
    unrelated to real user feedback. Those records are not review-backed and
    must not appear on the homepage, so they are dropped here.
    """
    Testimonial = apps.get_model("testimonials", "Testimonial")
    Testimonial.objects.all().delete()


def backfill_from_reviews(apps, schema_editor):
    """Create a pending testimonial candidate for every existing review.

    Required for Phase 13: existing reviews stay valid as property feedback and
    become *pending* testimonials so an admin can decide which become
    testimonial eligible - nothing is published automatically.
    """
    Testimonial = apps.get_model("testimonials", "Testimonial")
    Review = apps.get_model("Review", "Review")

    created = 0
    for review in Review.objects.all().iterator():
        Testimonial.objects.get_or_create(
            review_id=review.pk,
            defaults={"status": "pending"},
        )
        created += 1
    if created:
        print(f"  -> created {created} pending testimonial candidate(s) from existing reviews")


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("testimonials", "0001_initial"),
        ("Review", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            drop_legacy_manual_testimonials,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="testimonial",
            name="review",
            field=models.OneToOneField(
                help_text="The original user review this testimonial is derived from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonial",
                to="Review.Review",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("hidden", "Hidden"),
                ],
                db_index=True,
                default="pending",
                help_text="Moderation lifecycle status. Only 'approved' is public.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured testimonials are prioritised on the homepage.",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Manual ordering for the homepage. Lower numbers appear first.",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="admin_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal moderation note. Never exposed publicly.",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who last approved this testimonial.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_testimonials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the testimonial was last approved.",
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_from_reviews,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="name",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="role",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="text",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="image",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="order",
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["display_order", "-approved_at", "-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["status", "is_featured"],
                name="testimonial_status_016b89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["status", "created_at"],
                name="testimonial_status_1c4d7c_idx",
            ),
        ),
    ]