# Generated by Django 5.2.16 on 2026-09-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_review_backed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testimonial',
            new_name='testimonial_status_26d084_idx',
            old_name='testimonial_status_016b89_idx',
        ),
        migrations.RenameIndex(
            model_name='testimonial',
            new_name='testimonial_status_a11574_idx',
            old_name='testimonial_status_1c4d7c_idx',
        ),
    ]
