# Generated by Django 5.2.16 on 2026-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrate_user_profile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerverificationdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
