# Generated by Django 5.2.16 on 2026-08-18 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_address_remove_user_city_and_more'),
        ('properties', '0003_companyverificationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Booking', 'Booking'), ('Property', 'Property'), ('Payment', 'Payment'), ('System', 'System')], default='System', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Received', 'Received'), ('Confirmed', 'Confirmed'), ('Info', 'Info')], default='New', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('property_status', models.CharField(blank=True, max_length=50, null=True)),
                ('property_address', models.CharField(blank=True, max_length=500, null=True)),
                ('property_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('property_bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('property_size', models.CharField(blank=True, max_length=50, null=True)),
                ('property_nightly_price', models.CharField(blank=True, max_length=100, null=True)),
                ('property_image', models.CharField(blank=True, max_length=500, null=True)),
                ('property_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('property_added_date', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('check_in_date', models.CharField(blank=True, max_length=50, null=True)),
                ('check_out_date', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='properties.property')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
