# Generated by Django 5.2.16 on 2026-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NexaSpace', max_length=255)),
                ('site_tagline', models.CharField(default='Find Your Perfect Property', max_length=255)),
                ('contact_phone', models.CharField(default='+251 9XX XXX XXX', max_length=50)),
                ('contact_email', models.EmailField(default='info@nxrent.com', max_length=254)),
                ('office_address', models.TextField(default='Addis Ababa, Ethiopia')),
                ('social_website', models.URLField(default='http://localhost:5173/')),
                ('social_updates', models.URLField(default='http://localhost:5173/')),
                ('social_properties', models.URLField(default='http://localhost:5173/')),
                ('social_email', models.CharField(default='mailto:info@nxrent.com', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('footer_copyright', models.CharField(default='© 2025 NX Rental System. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
