# Generated by Django 5.2.16 on 2026-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_generalsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSetting',
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
