# Generated by Django 5.2.16 on 2026-08-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_generalsetting_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerverificationdocument',
            name='document_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_verification_documents/back/'),
        ),
        migrations.AddField(
            model_name='ownerverificationdocument',
            name='document_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_verification_documents/front/'),
        ),
    ]
