# Generated by Django 5.2.16 on 2026-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_email_on_reviews',
            field=models.BooleanField(default=True, help_text='When True, hides direct email on public ratings and reviews.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='share_phone_with_hosts',
            field=models.BooleanField(default=True, help_text='When True, phone & email visible. When False, hidden from other tenants.'),
        ),
    ]
