# Generated by Django 5.2.16 on 2026-09-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_back_image',
            field=models.ImageField(blank=True, help_text='National ID back image', null=True, upload_to='national_ids/back/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front_image',
            field=models.ImageField(blank=True, help_text='National ID front image', null=True, upload_to='national_ids/front/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National ID / FAN number', max_length=50, null=True),
        ),
    ]
