# Generated by Django 5.2.16 on 2026-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Received', 'Received'), ('Confirmed', 'Confirmed'), ('Info', 'Info')], default='New', max_length=20),
        ),
    ]
