# Generated by Django 5.2.16 on 2026-10-05 14:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerverificationdocument',
            name='document_back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document_back_image'),
        ),
        migrations.AlterField(
            model_name='ownerverificationdocument',
            name='document_front_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document_front_image'),
        ),
        migrations.AlterField(
            model_name='ownerverificationdocument',
            name='document_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_back_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='National ID back image', max_length=255, null=True, verbose_name='id_back_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_front_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='National ID front image', max_length=255, null=True, verbose_name='id_front_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
