# Generated by Django 5.2.16 on 2026-08-16 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housedetail',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.AddField(
            model_name='housedetail',
            name='distance_from_main_road',
            field=models.CharField(blank=True, help_text='Distance from the main road, e.g. "500 m", "1.5 km".', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housedetail',
            name='rules_to_follow',
            field=models.TextField(blank=True, help_text='Rental rules, e.g. "No smoking", "No pets", "Family only".', null=True),
        ),
        migrations.AddField(
            model_name='housedetail',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rooms in the property.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='kebele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Set by admins to indicate the company has been verified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Users authorised to manage this company and its listings.', related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, help_text='If set, this listing belongs to the specified company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.company'),
        ),
    ]
