# Generated by Django 5.2.16 on 2026-08-18 06:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_companyverificationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)')], default='ETB', help_text='Currency for the price and security deposit.', max_length=3),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name, e.g., 'Basic', 'Professional', 'Enterprise'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the plan features.', null=True)),
                ('target_type', models.CharField(choices=[('individual', 'Individual Owner'), ('company', 'Company')], help_text='Whether this plan is for individual owners or companies.', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Plan price in the specified currency.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)')], default='ETB', help_text='Currency for the plan price.', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing frequency.', max_length=20)),
                ('max_listings', models.PositiveIntegerField(blank=True, help_text='Maximum number of listings. NULL means unlimited.', null=True)),
                ('commission_rate_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission rate discount as a percentage (e.g., 10.00 = 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('featured_listing_limit', models.PositiveIntegerField(blank=True, help_text='Number of featured listings allowed per billing cycle. NULL means unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available for purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['-is_active', 'target_type', 'name'],
                'indexes': [models.Index(fields=['target_type', 'is_active'], name='properties__target__66f4f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(help_text='When the featured listing should start.')),
                ('end_at', models.DateTimeField(help_text='When the featured listing should end.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', help_text='Current status of the featured listing.', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price charged for this featured listing.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)')], default='ETB', help_text='Currency for the featured listing price.', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The property being featured.', on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='properties.property')),
            ],
            options={
                'verbose_name': 'Featured Listing',
                'verbose_name_plural': 'Featured Listings',
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['status', 'end_at'], name='properties__status_2bd6ff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='featured_listing_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', help_text='Current subscription status.', max_length=20)),
                ('current_period_start', models.DateTimeField(help_text='Start of the current billing period.')),
                ('current_period_end', models.DateTimeField(help_text='End of the current billing period.')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='If True, subscription will be canceled at the end of the current period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company. NULL if this subscription belongs to an individual.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='properties.company')),
                ('user', models.ForeignKey(blank=True, help_text='Individual owner. NULL if this subscription belongs to a company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='The subscription plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='properties.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='properties__user_id_25d89f_idx'), models.Index(fields=['company', 'status'], name='properties__company_482d2a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('user__isnull', False)), models.Q(('company__isnull', False), ('user__isnull', True)), _connector='OR'), name='subscription_belongs_to_exactly_one_recipient')],
            },
        ),
    ]
