# Generated by Django 5.2.16 on 2026-08-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_currency_subscriptionplan_featuredlisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.region')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['region__name', 'name'],
                'unique_together': {('name', 'region')},
            },
        ),
        # Rename existing char fields to legacy
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='legacy_city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='region',
            new_name='legacy_region',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='legacy_city',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='region',
            new_name='legacy_region',
        ),
        # Add the new ForeignKey fields
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='properties.city'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='properties.region'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.region'),
        ),
    ]
