# Generated by Django 5.2.16 on 2026-08-30 02:42

from django.db import migrations


def migrate_locations(apps, schema_editor):
    Region = apps.get_model('properties', 'Region')
    City = apps.get_model('properties', 'City')
    Property = apps.get_model('properties', 'Property')
    Company = apps.get_model('properties', 'Company')

    def get_or_create_location(region_name, city_name):
        if not region_name:
            region_name = 'Unknown Region'
        if not city_name:
            city_name = 'Unknown City'

        region_name = region_name.strip()
        city_name = city_name.strip()

        region, _ = Region.objects.get_or_create(name=region_name)
        city, _ = City.objects.get_or_create(name=city_name, region=region)
        return region, city

    for prop in Property.objects.all():
        region_name = prop.legacy_region
        city_name = prop.legacy_city
        if region_name or city_name:
            region, city = get_or_create_location(region_name, city_name)
            prop.region = region
            prop.city = city
            prop.save(update_fields=['region', 'city'])

    for comp in Company.objects.all():
        region_name = comp.legacy_region
        city_name = comp.legacy_city
        if region_name or city_name:
            region, city = get_or_create_location(region_name, city_name)
            comp.region = region
            comp.city = city
            comp.save(update_fields=['region', 'city'])

def reverse_migrate_locations(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_city_region_company_legacy_city_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_locations, reverse_migrate_locations),
    ]
