# Generated by Django 5.2.16 on 2026-08-30 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_city_region_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('listing_type', models.CharField(choices=[('house', 'House / Apartment'), ('car', 'Car / Vehicle')], help_text='The type of listing this category applies to.', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories cannot be selected for new listings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['listing_type', 'name'],
                'unique_together': {('name', 'listing_type')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Specific category of the property/vehicle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.category'),
        ),
    ]
