# Generated by Django 5.2.16 on 2026-09-10 17:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='purchased_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Billing cycle purchased at activation.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_commission_rate_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission discount snapshot (percentage).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_currency',
            field=models.CharField(blank=True, choices=[('ETB', 'Ethiopian Birr (ETB)'), ('USD', 'US Dollar (USD)')], default='', help_text='Currency actually paid at activation.', max_length=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_featured_listing_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Featured listing limit snapshot. NULL falls back to the current plan.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_max_listings',
            field=models.PositiveIntegerField(blank=True, help_text='Listing limit snapshot. NULL falls back to the current plan.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_name',
            field=models.CharField(blank=True, default='', help_text='Plan name snapshot taken at activation.', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchased_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price actually paid at activation.', max_digits=12, null=True),
        ),
    ]
