# Generated by Django 5.2.16 on 2026-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_subscription_purchased_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('rented', 'Rented'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
