# Generated by Django 5.2.16 on 2026-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_update_subscription_plans_assign_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, help_text='Normalized identity key used for deduplication.', max_length=100),
        ),
    ]
