# Generated by Django 5.2.16 on 2026-10-05 14:35

import cloudinary.models
import properties.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_feature_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='companyverificationdocument',
            name='document_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Uploaded document image or file.', max_length=255, null=True, verbose_name='document_file'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=properties.models.ListingImageField(max_length=255, verbose_name='image'),
        ),
    ]
