# Generated by Django 5.2.16 on 2026-08-18 06:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_property_currency_subscriptionplan_featuredlisting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, help_text='Auto-generated booking reference (e.g., BK-XXXXXXXX).', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Check-in date.')),
                ('end_date', models.DateField(help_text='Check-out date.')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Rental cost before deposit and fees.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Security deposit amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(help_text='Currency used for all financial amounts in this booking.', max_length=3)),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, help_text='Platform commission rate at the time of booking (as percentage).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total platform fee charged to the renter.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('owner_payout_amount', models.DecimalField(decimal_places=2, help_text='Amount the property owner/company will receive.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount the renter is expected to pay (base + deposit + platform_fee).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', help_text='Current booking status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The property being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
                ('recipient_company', models.ForeignKey(blank=True, help_text='Company receiving payout (if property belongs to a company).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_recipient', to='properties.company')),
                ('recipient_owner', models.ForeignKey(blank=True, help_text='Individual owner receiving payout (if property is individually owned).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_recipient', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(help_text='The tenant/renter.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_renter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['renter', 'status'], name='bookings_bo_renter__03bef2_idx'), models.Index(fields=['property', 'status'], name='bookings_bo_propert_92bdff_idx'), models.Index(fields=['start_date', 'end_date'], name='bookings_bo_start_d_8ecf7f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('recipient_company__isnull', True), ('recipient_owner__isnull', False)), models.Q(('recipient_company__isnull', False), ('recipient_owner__isnull', True)), _connector='OR'), name='booking_belongs_to_exactly_one_recipient')],
            },
        ),
    ]
