# Generated by Django 5.2.16 on 2026-08-31 18:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rental_type_and_conditional_dates'),
        ('properties', '0009_category_property_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_date_rules_by_rental_type',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_propert_e01a45_idx',
            old_name='bookings_bo_propert_7a1c2d_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, help_text='Move-out or return date; NULL for month-to-month houses.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner_payout_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='recipient_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_recipient', to='properties.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='recipient_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_type',
            field=models.CharField(choices=[('fixed_term', 'Fixed Term'), ('month_to_month', 'Month to Month')], default='fixed_term', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(help_text='Move-in or pickup date.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__gt', models.F('start_date')), ('rental_type', 'fixed_term')), models.Q(('end_date__isnull', True), ('rental_type', 'month_to_month')), _connector='OR'), name='booking_date_rules_by_rental_type'),
        ),
    ]
