# Generated by Django 5.2.16 on 2026-09-03 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=20)),
                ('actor_role', models.CharField(blank=True, default='', help_text='Snapshot of actor role at time of event.', max_length=20)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('confirmed_from_payment', 'Confirmed from payment'), ('expired', 'Expired'), ('completed', 'Completed'), ('admin_viewed', 'Admin viewed')], max_length=50)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='NULL indicates a system event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_audit_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_e6b818_idx'), models.Index(fields=['booking_reference', 'created_at'], name='bookings_bo_booking_4d9540_idx'), models.Index(fields=['action', 'created_at'], name='bookings_bo_action_866fb5_idx'), models.Index(fields=['actor', 'created_at'], name='bookings_bo_actor_i_444516_idx')],
            },
        ),
    ]
