# Generated by Django 5.2.16 on 2026-09-09 21:30

from django.db import migrations, models


def backfill_property_image(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    PropertyImage = apps.get_model("properties", "PropertyImage")

    for booking in Booking.objects.select_related("property").iterator():
        if booking.property_image:
            continue
        main_image = (
            PropertyImage.objects.filter(property_id=booking.property_id)
            .order_by("order", "id")
            .first()
        )
        if main_image:
            booking.property_image = main_image.image.url
            booking.save(update_fields=["property_image"])


def reverse_backfill(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.update(property_image="")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_legacy_booking_applicant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property_image',
            field=models.CharField(blank=True, default='', help_text="Snapshot of the property's main image at booking time.", max_length=500),
        ),
        migrations.RunPython(backfill_property_image, reverse_backfill),
    ]
