# Generated by Django 5.2.16 on 2026-10-05 14:35

import bookings.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingapplicantdocument',
            name='document',
            field=bookings.models.ApplicantDocumentField(max_length=255, verbose_name='document'),
        ),
    ]
